sylius_admin_order_comments_partial_comment_create:
    path: "/{orderId}/comments"
    methods: ["POST"]
    defaults:
        _controller: "sylius.order_comments_plugin.infrastructure.controller.ui.comment_form_action"

sylius_admin_order_comments_partial_comment_index:
    path: "/{orderId}/comments"
    methods: ["GET"]
    defaults:
        _controller: "sylius.controller.order_comment:indexAction"
        _sylius:
            paginate: false
            limit: false
            repository:
                method: findBy
                arguments:
                   - order: "expr:notFoundOnNull(service('sylius.repository.order').find($orderId))"
            template: "@SyliusOrderCommentsPlugin/index.html.twig"
