acme_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: SyliusOrderCommentsPlugin:Greeting:staticallyGreet
        name: ~

acme_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SyliusOrderCommentsPlugin:Greeting:dynamicallyGreet
        name: ~
