sylius_shop_order_comments_partial_comment_create:
    path: "/{orderId}/comments"
    methods: ["POST"]
    defaults:
        _controller: "sylius.order_comments_plugin.infrastructure.controller.ui.comment_form_action"

sylius_shop_order_comments_partial_comment_index:
    path: "/{number}/comments"
    methods: ["GET"]
    defaults:
        _controller: "sylius.controller.order_comment:indexAction"
        _sylius:
            paginate: false
            limit: false
            criteria:
                order: "expr:notFoundOnNull(service('sylius.repository.order').findOneByNumber($number))"
            template: "@SyliusOrderCommentsPlugin/index.html.twig"
